
CFLAGS+=-I../lib/


OBJS-y :=
-include libneighbour/Makefile

test: $(OBJS-y)

%.log: %.sh %.out
	@echo "==============="
	@echo "executing test $@"
	$< | tee $@

%.out : %.o ../lib/libneighbour/neighbour.o
	$(LINK.o) $^ $(LOADLIBES) $(LDLIBS) -o $@


