#!/bin/sh

hostname ${uts}

export TERM=screen
export PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/local/sbin:/usr/sbin
export HOME=/root

mount -n -t proc proc /proc
mount -n -t sysfs sys /sys


for fs in /run /var/run /var/tmp /var/log /tmp; do
    mount -t tmpfs tmpfs $fs -o rw,nosuid,nodev
done

mount -t devtmpfs none /dev

/etc/init.d/udev start

for intf in /sys/class/net/*; do
    intf=$(basename $intf)
    ip a l dev $intf 2> /dev/null >/dev/null || continue
    case $intf in
        lo|eth*|dummy*)
            ip link set up dev $intf
            ;;
    esac
done

rsyslogd

sysctl -w net.ipv6.conf.all.forwarding=1
sysctl -w net.ipv4.ip_forward=1

mkdir /var/run/quagga
chown quagga /var/run/quagga

mount -t tmpfs none /etc/quagga
echo 'bgpd=yes' > /etc/quagga/daemons
echo 'zebra=yes' >> /etc/quagga/daemons
echo 'zebra_options="  --daemon -A 127.0.0.1"' > /etc/quagga/debian.conf
echo 'bgpd_options="   --daemon -A 127.0.0.1"' >> /etc/quagga/debian.conf

cat > /etc/quagga/zebra.conf <<EOF
hostname $uts
password zebra
log file /var/log/bgpd.log
log stdout
!
EOF

cat > /etc/quagga/bgpd.conf <<EOF
hostname $uts
password zebra
log file /var/log/bgpd.log
log stdout
!
EOF

case $uts in
r1)
  echo R1
  ip a add 1.0.0.1/31 dev eth0
  ip a add 2001:1::0/127 dev eth0

  ip a add 1.0.1.254/24 dev dummy0
  ip a add 2001:2::1/24 dev dummy0
  ip link set dummy0 up

  cat >> /etc/quagga/zebra.conf <<EOF
interface dummy0
 link-detect
!
EOF

  cat >> /etc/quagga/bgpd.conf <<EOF
router bgp 1
 neighbor 2001:1::1 remote-as 2
 neighbor 2001:1::1 soft-reconfiguration inbound
 redistribute connected
 redistribute kernel
!

EOF

  ;;
r2)
  echo R2

  ip a add 1.0.0.0/31 dev eth0
  ip a add 2001:1::1/127 dev eth0
  ip a add 1.0.0.3/31 dev eth1
  ip a add 2001:1::3/127 dev eth1
  cat >> /etc/quagga/zebra.conf <<EOF
interface eth0
 link-detect
!
interface eth1
 link-detect
!
EOF
  cat >> /etc/quagga/bgpd.conf <<EOF
router bgp 2
 neighbor 2001:1::0 remote-as 1
 neighbor 2001:1::0 soft-reconfiguration inbound
 neighbor 2001:1::2 remote-as 3
 neighbor 2001:1::2 soft-reconfiguration inbound
 redistribute connected
 redistribute kernel
!
EOF


  ;;
r3)
  echo R3
  ip a add 1.0.0.2/31 dev eth0
  ip a add 2001:1::2/127 dev eth0

  ip a add 1.0.2.254/24 dev dummy0
  ip a add 2001:3::1/24 dev dummy0
  ip link set dummy0 up

  cat >> /etc/quagga/bgpd.conf <<EOF
router bgp 3
 neighbor 2001:1::3 remote-as 2
 neighbor 2001:1::3 soft-reconfiguration inbound
 redistribute connected
 redistribute kernel
!
EOF
  cat >> /etc/quagga/zebra.conf <<EOF
interface dummy0
!
EOF


  ;;
esac

/etc/init.d/quagga start

exec /sbin/getty -L ttyS1 -a root 9600 vt100
