#!/bin/sh

link1=$1
link2=$3
mac1=$2
mac2=$4

ip link set $link1 up
ip link set $link2 up

ip link add link $link1 name $link1.2000 type vlan id 2000
ip link add link $link2 name $link2.2000 type vlan id 2000

ip link set $link1.2000 up
ip link set $link2.2000 up

ip link set $link1.2000 address $mac1
ip link set $link2.2000 address $mac2

ip addr add 1.0.0.1/31 dev $link1.2000
ip addr add 2001:1::1/127 dev $link1.2000
ip addr add 1.0.0.3/31 dev $link2.2000
ip addr add 2001:1::3/127 dev $link2.2000

#####

/usr/sbin/bird &
/usr/sbin/bird6 &
