#!/bin/sh

link1=$1
mac1=$2

ip link set $link1 up
ip link add link $link name $link.2000 type vlan id 2000
ip link set $link.2000 address $mac1
ip link set $link.2000 up

ip addr add 1.2.3.5/24 dev $link.2000
ip route add 1.2.4.0/24 via 1.2.3.4
ip addr add 2001:3::5/48 dev $link.2000
ip route add 2001:4::/48 via 2001:3::4
